### ISSUE TITLE
Not-needed extra delegation when it is already done

### ISSUE THREAD

**Issue by eboadom** [bgd-labs/aave-governance-v3-interface#55]
Scenario is the following:
- The connected wallet is giving proposition power to address A on AAVE, but not giving delegation for stkAAVE and aAAVE.
- The new delegation action is giving to address A proposition power on the missing assets: aAAVE, stkAAVE.
- When confirming, it triggers signature (plus I guess passing the data on the batch tx of delegation) for AAVE, even if no change is intended from the current state.

This adds totally unnecessary extra gas to the transaction.

*Solution*: whenever there is no change on certain type of delegation and asset, nothing should be signed/submitted for it.

**Comment by Argeare5** [comment]
@eboadom are you sure about that?

because your scenario works as it should for me

**Comment by eboadom** [comment]
Pretty sure, but I can't reproduce now

**Comment by Argeare5** [comment]
It may be related to the logic of supporting the ENS name in the input, need to check
