### ISSUE TITLE
voters box jumpes back to top every refresh

### ISSUE THREAD

**Issue by sakulstra** [bgd-labs/aave-governance-v3-interface#57]
the voters box is jumping back to the top on every refresh

**Comment by Argeare5** [comment]
It’s not clear what you’re talking about, add more details

**Comment by sakulstra** [comment]
![image](https://github.com/bgd-labs/aave-governance-v3-interface/assets/4396533/64d39355-390f-48bb-a4f0-434637c8be9b)

When you scroll down in the box displaying the voters, after a few second it will jump back to the top.
