### ISSUE TITLE
Refund of the cancellation fee that the creator pays when creating the proposal from the UI

### ISSUE THREAD

**Issue by Argeare5** [bgd-labs/aave-governance-v3-interface#65]
My idea is to expand the functionality of the UI and add to it the possibility of returning a fee for creating an proposal. @NikitaMesh  and I thought about it and we see something like this flow and design:

Flow:

1. Connect wallet
2. Button in the window of the connected wallet (if this connected address created at least one proposal)

<img width="843" alt="Снимок экрана 2024-01-30 в 09 54 40" src="https://github.com/bgd-labs/aave-governance-v3-interface/assets/25132555/2c80338a-6386-41ec-b12e-205a0ca647d9">

3. Window in which the address will be able to see the creator of what proposal it is, and can see the availability of whether it can return the fee for this proposal.

<img width="911" alt="Снимок экрана 2024-01-30 в 15 53 56" src="https://github.com/bgd-labs/aave-governance-v3-interface/assets/25132555/63602f2e-cb78-4d21-bb33-996e1c26fe53">

4. Default transaction window like in representation or delegation.

5. There will also be a button on the proposal details screen for a cancellation fee refund (creator and when it's available only).

I think this will be enough. 

Approximate implementation time:
Design: 1-2 days
Implementation: 2-4 days
(in parallel)

What do you think @eboadom @kyzia551 ?

**Comment by eboadom** [comment]
1. In terms of text, better `Claim creation fees` for the link, and could it be better below "Manage delegations"?
2. It should have an icon next to the link, to be consistent with the others
3. "Claimed", not "Returned"
4. "Claim", not "Return"
5. "In progress" not "Return later"
6. On tooltip: `When you create a governance proposal, a small ETH guarantee is included to protect against spam. You can claim this guarantee here, once the proposal has finished without being cancelled`
7. Will the "Claim creation fees"  be hidden if the address never created a proposal?

**Comment by Argeare5** [comment]
@eboadom @kyzia551 @NikitaMesh please take a look, all fixes done (app mode switcher added to settings button)

link: https://aave-governance-v3-interface-git-feat-return-fees-bgd-labs.vercel.app/
